# Generated by Django 5.0.1 on 2025-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='buy',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Покупка'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sell',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Продажа'),
        ),
    ]
