# Generated by Django 4.2.3 on 2025-02-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Курс валют', 'verbose_name_plural': 'Курсы валют'},
        ),
        migrations.AddField(
            model_name='exchanger',
            name='address_map',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default='usd', max_length=40, unique=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='exchanger',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='exchanger',
            name='telephone',
            field=models.CharField(blank=True, help_text='+38096-123-45-67', max_length=16),
        ),
    ]
