# Generated by Django 4.2.3 on 2025-02-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_cartitem_options_exchanger_address_map_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchanger',
            name='exchanger_info',
        ),
        migrations.RemoveField(
            model_name='exchanger',
            name='telephone',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='min_sum',
            field=models.IntegerField(default=100),
        ),
    ]
