# Generated by Django 5.0.1 on 2025-02-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_remove_exchanger_exchanger_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='min_sum',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sum',
            field=models.IntegerField(default=100, verbose_name='Сумма от 100 до 10000'),
        ),
    ]
