# Generated by Django 5.0.1 on 2025-02-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_remove_cartitem_min_sum_alter_cartitem_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Принятый'), ('completed', 'Выполнен'), ('new', 'Новый'), ('cancel', 'Сancel')], default='new', max_length=10)),
                ('сlients_telephone', models.CharField(help_text='+38096-123-45-67', max_length=16)),
                ('address_exchanger', models.CharField(blank=True, max_length=100, verbose_name='Адрес Брони')),
                ('currency_name', models.CharField(blank=True, max_length=40, verbose_name='Валюта')),
                ('buy_or_sell', models.CharField(blank=True, max_length=8)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Курс')),
                ('order_sum', models.IntegerField(verbose_name='Сумма заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
